// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQsvWjtvgLxPuXt4BwNSN5vNyrSRh7Hk',
    appId: '1:545949761329:web:5d2b901df6abfa614afa10',
    messagingSenderId: '545949761329',
    projectId: 'chatapp-lernatelier',
    authDomain: 'chatapp-lernatelier.firebaseapp.com',
    storageBucket: 'chatapp-lernatelier.appspot.com',
    measurementId: 'G-NEX5TK0VNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNwSyo4zJt0KUTIDtJDPXeB-zfovyGhw',
    appId: '1:545949761329:android:9fd89b247ab7dd954afa10',
    messagingSenderId: '545949761329',
    projectId: 'chatapp-lernatelier',
    storageBucket: 'chatapp-lernatelier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY30BePQv4HrS3XIrxJPUO3W5jjTMNvHA',
    appId: '1:545949761329:ios:570c34ae6e42c47b4afa10',
    messagingSenderId: '545949761329',
    projectId: 'chatapp-lernatelier',
    storageBucket: 'chatapp-lernatelier.appspot.com',
    iosClientId: '545949761329-k3cvrad9jm28a2u7pnv2sl24kiqqu6kl.apps.googleusercontent.com',
    iosBundleId: 'ch.bbbaden.chatapp',
  );
}
